-- CREATING A SUMMARY DATASET FOR ANALYSIS USING AN EXISTING DATA TABLE
-- THE PURPOSE OF THIS TABLE IS TO CREATE A SUMMARY BY YEAR AND ACCOUNT ID OF AN ALREADY EXIST DATA TABLE 

INSERT INTO YEAR_SUMMARY
(ACCID, FYEAR,SDSG, CURRTYPE,ADATE,ATIME,AUSER,AORG,CODERV,CURRDESC,OPENBAL,NETP1,NETP2,NETP3,NETP4,NETP5)

SELECT 
AR.ACCID, AR.FYEAR,SDSG,'F' AS AR.CURRTYPE,AR.ADATE,AR.ATIME,AR.AUSER,AR.AORG,AR.CODERV,AR.CURRDESC,AR.OPENBAL,AR.NETP1,AR.NETP2,
AR.NETP3,AR.NETP4,AR.NETP5
FROM ACCOUNT_RECORDS AR
JOIN
 ( SELECT 
  ACCID, FYEAR,
  SUM(AMT) AS OPENBAL,
  SUM(CASE WHEN FPRD = 1 THEN AMT ELSE 0 END) AS NETP1,
  SUM(CASE WHEN FPRD = 2 THEN AMT ELSE 0 END) AS NETP2,
  SUM(CASE WHEN FPRD = 3 THEN AMT ELSE 0 END) AS NETP3,
  SUM(CASE WHEN FPRD = 4 THEN AMT ELSE 0 END) AS NETP4,
  SUM(CASE WHEN FPRD = 5 THEN AMT ELSE 0 END) AS NETP5,
  
  FROM 
   ACCOUNT_RECORDS
   GROUP BY 
   ACCID, FYEAR
   AR ON AR.ACCID = AR.ACCID AND GL.FYEAR = FYEAR



